# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded anatra           1.0 \
  [list source [file join $dir anatra.tcl]]
package ifneeded anatra_arg       1.0 \
  [list source [file join $dir anatra_arg.tcl]]
package ifneeded anatra_traj      1.0 \
  [list source [file join $dir anatra_traj.tcl]]
package ifneeded anatra_structure 1.0 \
  [list source [file join $dir anatra_structure.tcl]]
package ifneeded anatra_selection 1.0 \
  [list source [file join $dir anatra_selection.tcl]]
package ifneeded anatra_common    1.0 \
  [list source [file join $dir anatra_common.tcl]]
